"""add owner_id

Revision ID: 0c8632af2c40
Revises: 61e347c910ec
Create Date: 2026-09-06 22:40:32.025012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8632af2c40'
down_revision: Union[str, Sequence[str], None] = '61e347c910ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('owner_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.add_column('batches', sa.Column('owner_id', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_batches_owner_id'), 'batches', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batches_owner_id'), table_name='batches')
    op.drop_column('batches', 'owner_id')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_column('assets', 'owner_id')
    # ### end Alembic commands ###
