"""asset batch_id and size_bytes

Revision ID: 61e347c910ec
Revises: 580252f3ae0d
Create Date: 2026-09-06 19:44:29.200246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e347c910ec'
down_revision: Union[str, Sequence[str], None] = '580252f3ae0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('size_bytes', sa.BigInteger(), nullable=False))
    op.drop_column('assets', 'bytes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('bytes', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('assets', 'size_bytes')
    # ### end Alembic commands ###
