"""composite unique owner_id sha256

Revision ID: a7d0ed86a759
Revises: 0c8632af2c40
Create Date: 2026-09-06 23:36:16.255550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d0ed86a759'
down_revision: Union[str, Sequence[str], None] = '0c8632af2c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_sha256'), table_name='assets')
    op.create_index(op.f('ix_assets_sha256'), 'assets', ['sha256'], unique=False)
    op.create_unique_constraint(None, 'assets', ['owner_id', 'sha256'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='unique')
    op.drop_index(op.f('ix_assets_sha256'), table_name='assets')
    op.create_index(op.f('ix_assets_sha256'), 'assets', ['sha256'], unique=True)
    # ### end Alembic commands ###
